spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    generate-ddl: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  threshold:
    console: INFO
  level:
    org:
      hibernate:
        type: INFO
        stat: INFO
