spring:
  jpa:
    show-sql: true
    #    hibernate:
    #      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    #        generate_statistics: true
    open-in-view: false
    generate-ddl: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  threshold:
    console: TRACE
  level:
    org:
      hibernate:
        type: INFO
        stat: INFO
