name: API Tests

on:
  workflow_dispatch:

env:
  CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  run-api-test:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-20.04

    steps:
      - name: Checking out
        uses: actions/checkout@v3
      - name: Authenticating
        uses: google-github-actions/auth@v1
        id: auth
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.CICD_SA_EMAIL_ADDRESS }}
          token_format: id_token
          id_token_audience: ${{ secrets.CLOUD_RUN_BACKEND_URL }}
          id_token_include_email: true
      - name: Run API tests
        uses: matt-ball/newman-action@v1.0.4
        with:
          collection: Bodleian.postman_collection.json
          envVar: '[{ "key": "HOST", "value": "${{ secrets.CLOUD_RUN_BACKEND_URL }}" }, { "key": "TOKEN", "value": "${{ steps.auth.outputs.id_token }}" }]'
#          timeoutRequest: 3
          bail: true


