name: Build main

on:
  push:
    branches: [main]
    tags-ignore: ["**"]
  workflow_dispatch:

env:
  CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  security-can:
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out
        uses: actions/checkout@v3
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@0.3.0
        # continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      # not sure about codeQl.
      # with:
      #   args: --sarif-file-output=snyk.sarif
      # - name: Upload result to GitHub Code Scanning
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: snyk.sarif
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.5.0
        with:
          scan-type: "fs"
          ignore-unfixed: false
          format: "table"
          exit-code: "1"
          severity: "CRITICAL"

  qa:
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.14.0"
      - name: Install dependencies
        run: go mod download
      # - name: Uploading coverage
      #   uses: codacy/codacy-coverage-reporter-action@v1
      #   with:
      #     api-token: ${{ secrets.CODACY_API_TOKEN }}
      #     coverage-reports: ./target/site/jacoco/jacoco.xml
      #   env:
      #     CODACY_PROJECT_NAME: "bodleian-service-tmp"
      #     CODACY_ORGANIZATION_PROVIDER: "gh"
      #     CODACY_USERNAME: "${{ github.repository_owner }}"

  build-container:
    needs:
      - qa

    permissions:
      id-token: write

    runs-on: ubuntu-20.04

    steps:
      - name: Checking out
        uses: actions/checkout@v3
      - name: Authenticating
        uses: google-github-actions/auth@v0.8.0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.CICD_SA_EMAIL_ADDRESS }}
          token_format: "access_token"
      - name: Setting up GCP environment
        uses: google-github-actions/setup-gcloud@v0.6.0
      - name: Setting up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Containerizing
        id: containerizing
        run: ./scripts/containerize.sh
      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@0.5.0
      #   with:
      #     image-ref: ${{steps.containerizing.outputs.image-name }}
      #     format: "table"
      #     exit-code: "1"
      #     ignore-unfixed: true
      #     vuln-type: "os,library"
      #     severity: "CRITICAL,HIGH"
      - name: Pushing image
        id: push
        run: ./scripts/containerize.sh
        env:
          OUTPUT_MODE: push
      - name: Deploying to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0.10.0
        with:
          image: ${{steps.push.outputs.image-name }}
          service: ${{ secrets.CLOUD_RUN_SERVICE }}
          region: ${{ secrets.CLOUD_RUN_REGION }}
          timeout: 30 # allow enough time to startup container
          no_traffic: true
          tag: main-latest
      - name: Check if service is up
        run: |
          curl -H "Authorization: Bearer $(gcloud auth print-identity-token)" "${{ steps.deploy.outputs.url }}/health"
