name: Receive pull request

on:
  pull_request:

# TODO: Update pull request, e.g.,
# - name: Update Pull Request
#   uses: actions/github-script@v6
#   if: github.event_name == 'pull_request'
#   with:
#     script: |
#       const output = `
#       #### Hadolint: \`${{ steps.hadolint.outcome }}\`
#       \`\`\`
#       ${process.env.HADOLINT_RESULTS}
#       \`\`\`
#       `;

#       github.rest.issues.createComment({
#         issue_number: context.issue.number,
#         owner: context.repo.owner,
#         repo: context.repo.repo,
#         body: output
#       })

jobs:
  security-scan-code:
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.6.2
        with:
          scan-type: "fs"
          ignore-unfixed: false
          format: "table"
          exit-code: "1"
          severity: "CRITICAL"

  qa:
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.14.0"
      - name: Install dependencies
        run: go mod download
      - name: Testing
        run: go test
      - name: Checking Dockerfile
        uses: hadolint/hadolint-action@v2.1.0
        with:
          verbose: true

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.14.0"
      - name: Install dependencies
        run: go mod download
      - name: Building
        run: go build -o bodleian-service

  mark-pr:
    needs:
      - qa
      - build
      - security-scan-code
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-add-labels@v1.1.3
        with:
          labels: |
            linted
            qaed
            secure
            ready-for-review
          token: ${{ secrets.GH_TOKEN_FOR_LABELING }}
          number: ${{ github.event.number }}
