name: Testing

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  testing:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-20.04

    steps:
      - name: Checking out
        uses: actions/checkout@v3
      - name: Authenticating
        uses: google-github-actions/auth@v0.7.3
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: bodleian-backend-cicd@bodleian-398addce.iam.gserviceaccount.com
          # token_format: "access_token"
          token_format: "id_token"
          id_token_audience: https://google.com
      - name: Setting up GCP environment
        uses: google-github-actions/setup-gcloud@v0.6.0
      - run: gcloud auth print-identity-token
